### PR TITLE
Allows to open file projects from a different path than the current one ...

### PR DESCRIPTION
**Pull request by rastersoft**
...without changing the current working path. This would allow to have several projects opened at the same time. Still, this patch needs some review before being merged to ensure that it works as expected and doesn't have undesired effects.

The second commit adds several fixes that makes it work better.

### CODE REVIEW

**Comment by rastersoft** [comment]
BTW: a possible modification is to create a class derived from ProjectMember that could be called ProjectMemberWithFile, that contains the methods build_absolute_path and get_relative_path.

**Comment by rastersoft** [comment]
I will try the other approach.

**Comment by LSenf** [comment]
@rastersoft Just thought I should add something like this this morning :)
I think the cleanest way to work with relative directories is GLib.File.get_relative_path and GLib.File.resolve_relative_path.
I don't think it's a good idea to subclass ProjectMember, as only few projectmembers only refer to a single file.
How about using a small class for representing paths that contains a reference to the project and can provide both relative and absolute paths, like this:

public class ProjectFileRef {
  private Project project;
  private string rel_path;
  public ProjectFileRef.from_abs (Project project, string absolute_path) {
    rel_path = project.file.get_relative_path (File.from_path(absolute_path));
    this.project = project;
  }
  public ProjectFileRef.from_rel (string rel_path) {
    this.rel_path = rel_path;
    this.project = project;
  }
  public string get_rel() {
    return rel_path;
  }
  public string get_abs() {
    .....
  }

}

This could be used for all file references occurring in all project members

**Comment by rastersoft** [comment]
I like it! Tomorrow I have a lot of work, but maybe the weekend I will be able to work on this, if you want.

**Pull request closed without merging**
