### PR TITLE
Color scheme

### PR DESCRIPTION
**Pull request by alsoijw**
Added ability to select color schemes.
Fixed a problem loading scheme.

### CODE REVIEW

**Comment by inizan-yannick** [comment]
unfortunately, doesn't work
```
(valama:12312): GLib-GIO-CRITICAL **: g_settings_set_value: key 'current-color-scheme' in 'org.valama' expects type 's', but a GVariant of type '(null)' was given
```

**Comment by alsoijw** [comment]
inizan-yannick, you must rebuild and reinstall Valama.

**Comment by inizan-yannick** [comment]
@alsoijw it's your build.

**Comment by alsoijw** [comment]
@inizan-yannick I can't understand you. My English is too bad.

**Comment by inizan-yannick** [comment]
I've deleted all directories related to valama, cloned your repository and build it. I've the same error, without modification of color scheme

**Comment by alsoijw** [comment]
@inizan-yannick  after changing the color scheme reopen the file.

**Comment by alsoijw** [comment]
Where can I find a list of all open SuperSourceView?

**Comment by inizan-yannick** [comment]
color scheme changed, thanks :)

**Comment by LSenf** [comment]
Could you please automatically update all source files when the theme is changed?
This should be possible via signals (Connect each SuperSourceView on construction to that signal).
Once this is finished, I will merge your commits :)

Also, I recommend working on valamang for new features.

**Comment by alsoijw** [comment]
I can say what event to use? I tried to override a property in a class inherited from SourceBuffer.  Changing this property will cause the event. But the code is not building because of an error in the c code. The fact that the property is not virtual style_scheme. Will there be something bad if I create another class inherited from SourceBuffer which will be inherited from the class that cause the event?

**Pull request closed without merging**
